Next.
Signed-off-by: Oleksandr Andriienko <oandriie@redhat.com>

diff --git a/components/minio/development/minio-tenant-installed-check-job.yaml b/components/minio/development/minio-tenant-installed-check-job.yaml
--- a/components/minio/development/minio-tenant-installed-check-job.yaml
+++ b/components/minio/development/minio-tenant-installed-check-job.yaml
@@ -14,22 +14,24 @@ spec:
             - /bin/bash
             - -c
             - |
-              echo "Waiting for minio tenant to be present"
-              oc get pods -n tekton-results
-              numOfAttempts=40
-              ns=tekton-results
-              i=0
-              while [ -z "$(oc get pods -l "app=minio" -n "$ns" --no-headers -o custom-columns=':metadata.name')" ]; do \
-                printf '.'; sleep 5; \
-                i=$((i+1)) \
-                if [[ $i -eq "${numOfAttempts}" ]]; then \
-                  printf "\n[ERROR] Pod %s not found by timeout \n" "app=minio" >&2 \
-                  oc -n "$ns" get events | grep Warning \
-                  exit 1 \
-                fi \
+              echo "Waiting for minio tenant to be present";
+              oc get pods -n tekton-results;
+              numOfAttempts=40;
+              ns=tekton-results;
+              i=0;
+              
+              while [ -z "$(oc get pods -l app=minio -n $ns --no-headers -o custom-columns=':metadata.name')" ]; do
+                printf '.';
+                sleep 5;
+                i=$((i+1));
+                if [[ $i -eq "${numOfAttempts}" ]]; then
+                  printf "\n[ERROR] Pod %s not found by timeout \n" "app=minio" >&2;
+                  oc -n "$ns" get events | grep Warning;
+                  exit 1;
+                fi
               done
           imagePullPolicy: Always
-          name: patch-chains-certs
+          name: minio-tenant-checker
       dnsPolicy: ClusterFirst
       restartPolicy: OnFailure
       # terminationGracePeriodSeconds: 30
